name: unknown
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  dio_http2_adapter: ^2.4.0


  pretty_dio_logger: ^1.3.1
  flutter_staggered_grid_view: ^0.7.0
  auto_route: ^7.8.2
  rxdart: ^0.27.7
  provider: ^6.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  network_info_plus: ^4.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.1
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/image/
