default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
  end

  lane :release do
    build_app(scheme: "Runner",
              workspace: "Runner.xcworkspace",
              include_bitcode: true)
  end


  end
