default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    sh "flutter build apk"
  end

  desc "My awesome app"
      lane :distribute do
          build_android_app(...)
          # build_android_app is a built-in fastlane action.
          release = firebase_app_distribution(
              app: "1:123456789:android:abcd1234",
              testers: "tester1@company.com, tester2@company.com",
              release_notes: "Lots of amazing new features to test out!"
          )
  end

 end