name: Deploy To App Distribution

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build_deploy_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'


      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Debug Service Account JSON
        run: echo "${{ secrets.YOUR_SERVICE_ACCOUNT_CREDENTIALS }}"

      - name: Install Dependencies
        run: flutter pub get


      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: android

      - run: bundle exec fastlane ${{ github.event.inputs.lane || 'test' }}
        working-directory: android

      - run: bundle exec fastlane ${{ github.event.inputs.lane || 'build_ipa' }}
        working-directory: ios

      - name : Build Release
        run : flutter build apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.GOOGLE_SERVICES_JSON}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk

