name: Deploy To App Distribution

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:


  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Log in to Firebase
        run: |
          echo "${{secrets.FIREBASE_TOKEN}}" | firebase login --interactive --no-localhost

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - run: flutter clean
      - name: Install Dependencies
        run: flutter pub get

      - run: flutter build ios --release --no-codesign

      - name: Upload to Firebase Distribution
        run: |
          firebase appdistribution:distribute "build/ios/iphoneos/Runner.app" --token "${{secrets.FIREBASE_TOKEN}}" --app "${{secrets.FIREBASE_APP_ID_IOS}}" --groups 'testers'





